// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: YM.Common/CommonMessage.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PKeyString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PKeyString) Reset() {
	*x = PKeyString{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PKeyString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKeyString) ProtoMessage() {}

func (x *PKeyString) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKeyString.ProtoReflect.Descriptor instead.
func (*PKeyString) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{0}
}

func (x *PKeyString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PKeyInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PKeyInt) Reset() {
	*x = PKeyInt{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PKeyInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKeyInt) ProtoMessage() {}

func (x *PKeyInt) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKeyInt.ProtoReflect.Descriptor instead.
func (*PKeyInt) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{1}
}

func (x *PKeyInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PKeyLong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PKeyLong) Reset() {
	*x = PKeyLong{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PKeyLong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKeyLong) ProtoMessage() {}

func (x *PKeyLong) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKeyLong.ProtoReflect.Descriptor instead.
func (*PKeyLong) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{2}
}

func (x *PKeyLong) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{3}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Dictionary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*KeyValuePair        `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dictionary) Reset() {
	*x = Dictionary{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dictionary) ProtoMessage() {}

func (x *Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dictionary.ProtoReflect.Descriptor instead.
func (*Dictionary) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{4}
}

func (x *Dictionary) GetData() []*KeyValuePair {
	if x != nil {
		return x.Data
	}
	return nil
}

type NullableBool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableBool) Reset() {
	*x = NullableBool{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableBool) ProtoMessage() {}

func (x *NullableBool) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableBool.ProtoReflect.Descriptor instead.
func (*NullableBool) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{5}
}

func (x *NullableBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type NullableDecimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableDecimal) Reset() {
	*x = NullableDecimal{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableDecimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableDecimal) ProtoMessage() {}

func (x *NullableDecimal) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableDecimal.ProtoReflect.Descriptor instead.
func (*NullableDecimal) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{6}
}

func (x *NullableDecimal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NullableUInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableUInt) Reset() {
	*x = NullableUInt{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableUInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableUInt) ProtoMessage() {}

func (x *NullableUInt) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableUInt.ProtoReflect.Descriptor instead.
func (*NullableUInt) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{7}
}

func (x *NullableUInt) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ResponseBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBase) Reset() {
	*x = ResponseBase{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBase) ProtoMessage() {}

func (x *ResponseBase) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBase.ProtoReflect.Descriptor instead.
func (*ResponseBase) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseBase) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ResponseBaseWithInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	PKeyInt       int32                  `protobuf:"varint,2,opt,name=PKeyInt,proto3" json:"PKeyInt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBaseWithInt) Reset() {
	*x = ResponseBaseWithInt{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBaseWithInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBaseWithInt) ProtoMessage() {}

func (x *ResponseBaseWithInt) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBaseWithInt.ProtoReflect.Descriptor instead.
func (*ResponseBaseWithInt) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseBaseWithInt) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseBaseWithInt) GetPKeyInt() int32 {
	if x != nil {
		return x.PKeyInt
	}
	return 0
}

type ResponseBaseWithLong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	PKeyLong      int64                  `protobuf:"varint,2,opt,name=PKeyLong,proto3" json:"PKeyLong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBaseWithLong) Reset() {
	*x = ResponseBaseWithLong{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBaseWithLong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBaseWithLong) ProtoMessage() {}

func (x *ResponseBaseWithLong) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBaseWithLong.ProtoReflect.Descriptor instead.
func (*ResponseBaseWithLong) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseBaseWithLong) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseBaseWithLong) GetPKeyLong() int64 {
	if x != nil {
		return x.PKeyLong
	}
	return 0
}

type ResponseBaseWithString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	PKeyString    string                 `protobuf:"bytes,2,opt,name=PKeyString,proto3" json:"PKeyString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBaseWithString) Reset() {
	*x = ResponseBaseWithString{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBaseWithString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBaseWithString) ProtoMessage() {}

func (x *ResponseBaseWithString) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBaseWithString.ProtoReflect.Descriptor instead.
func (*ResponseBaseWithString) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseBaseWithString) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseBaseWithString) GetPKeyString() string {
	if x != nil {
		return x.PKeyString
	}
	return ""
}

type ResponseBaseWithKeyDictionary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Data          *Dictionary            `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBaseWithKeyDictionary) Reset() {
	*x = ResponseBaseWithKeyDictionary{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBaseWithKeyDictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBaseWithKeyDictionary) ProtoMessage() {}

func (x *ResponseBaseWithKeyDictionary) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBaseWithKeyDictionary.ProtoReflect.Descriptor instead.
func (*ResponseBaseWithKeyDictionary) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseBaseWithKeyDictionary) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseBaseWithKeyDictionary) GetData() *Dictionary {
	if x != nil {
		return x.Data
	}
	return nil
}

type NullableInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableInt) Reset() {
	*x = NullableInt{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableInt) ProtoMessage() {}

func (x *NullableInt) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableInt.ProtoReflect.Descriptor instead.
func (*NullableInt) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{13}
}

func (x *NullableInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NullableTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableTimestamp) Reset() {
	*x = NullableTimestamp{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableTimestamp) ProtoMessage() {}

func (x *NullableTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableTimestamp.ProtoReflect.Descriptor instead.
func (*NullableTimestamp) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{14}
}

func (x *NullableTimestamp) GetData() *timestamppb.Timestamp {
	if x != nil {
		return x.Data
	}
	return nil
}

type GenericLongCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericLongCollection) Reset() {
	*x = GenericLongCollection{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericLongCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericLongCollection) ProtoMessage() {}

func (x *GenericLongCollection) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericLongCollection.ProtoReflect.Descriptor instead.
func (*GenericLongCollection) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{15}
}

func (x *GenericLongCollection) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type GenericIntCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int32                `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericIntCollection) Reset() {
	*x = GenericIntCollection{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericIntCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericIntCollection) ProtoMessage() {}

func (x *GenericIntCollection) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericIntCollection.ProtoReflect.Descriptor instead.
func (*GenericIntCollection) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{16}
}

func (x *GenericIntCollection) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type GenericStringCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericStringCollection) Reset() {
	*x = GenericStringCollection{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericStringCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericStringCollection) ProtoMessage() {}

func (x *GenericStringCollection) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericStringCollection.ProtoReflect.Descriptor instead.
func (*GenericStringCollection) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{17}
}

func (x *GenericStringCollection) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ResponseBaseWithBool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBaseWithBool) Reset() {
	*x = ResponseBaseWithBool{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBaseWithBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBaseWithBool) ProtoMessage() {}

func (x *ResponseBaseWithBool) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBaseWithBool.ProtoReflect.Descriptor instead.
func (*ResponseBaseWithBool) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{18}
}

func (x *ResponseBaseWithBool) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseBaseWithBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type PageFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageIndex     int32                  `protobuf:"varint,2,opt,name=PageIndex,proto3" json:"PageIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageFilter) Reset() {
	*x = PageFilter{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageFilter) ProtoMessage() {}

func (x *PageFilter) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageFilter.ProtoReflect.Descriptor instead.
func (*PageFilter) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{19}
}

func (x *PageFilter) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageFilter) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

type ChunkStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkStream) Reset() {
	*x = ChunkStream{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkStream) ProtoMessage() {}

func (x *ChunkStream) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkStream.ProtoReflect.Descriptor instead.
func (*ChunkStream) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{20}
}

func (x *ChunkStream) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateStart     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=DateStart,proto3" json:"DateStart,omitempty"`
	DateEnd       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=DateEnd,proto3" json:"DateEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{21}
}

func (x *DateRange) GetDateStart() *timestamppb.Timestamp {
	if x != nil {
		return x.DateStart
	}
	return nil
}

func (x *DateRange) GetDateEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.DateEnd
	}
	return nil
}

type NullableLong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableLong) Reset() {
	*x = NullableLong{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableLong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableLong) ProtoMessage() {}

func (x *NullableLong) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableLong.ProtoReflect.Descriptor instead.
func (*NullableLong) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{22}
}

func (x *NullableLong) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NullableDouble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableDouble) Reset() {
	*x = NullableDouble{}
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableDouble) ProtoMessage() {}

func (x *NullableDouble) ProtoReflect() protoreflect.Message {
	mi := &file_YM_Common_CommonMessage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableDouble.ProtoReflect.Descriptor instead.
func (*NullableDouble) Descriptor() ([]byte, []int) {
	return file_YM_Common_CommonMessage_proto_rawDescGZIP(), []int{23}
}

func (x *NullableDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_YM_Common_CommonMessage_proto protoreflect.FileDescriptor

var file_YM_Common_CommonMessage_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x59, 0x4d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x59, 0x4d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0a, 0x50,
	0x4b, 0x65, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x1f, 0x0a, 0x07, 0x50, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x20, 0x0a, 0x08, 0x50, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61,
	0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x0a, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x59, 0x4d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x24, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x4e,
	0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x24, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x55, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x43,
	0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x61, 0x73, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x49, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x4b, 0x65,
	0x79, 0x49, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x4b, 0x65, 0x79,
	0x49, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x50, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x6e, 0x67, 0x22, 0x4c, 0x0a, 0x16, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x61, 0x73, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x4b, 0x65,
	0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50,
	0x4b, 0x65, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x5e, 0x0a, 0x1d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x61, 0x73, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79,
	0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x59,
	0x4d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x23, 0x0a, 0x0b, 0x4e, 0x75, 0x6c,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x43,
	0x0a, 0x11, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x4c, 0x6f,
	0x6e, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x49,
	0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x61, 0x73, 0x65, 0x57, 0x69, 0x74, 0x68, 0x42, 0x6f, 0x6f, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x0a, 0x50, 0x61, 0x67,
	0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x23, 0x0a, 0x0b, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x7b, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x44, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x34, 0x0a,
	0x07, 0x44, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x44, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4c,
	0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x4e, 0x75, 0x6c,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x33, 0x5a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x59, 0x4d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x70, 0x62, 0xaa, 0x02, 0x11, 0x59, 0x4d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_YM_Common_CommonMessage_proto_rawDescOnce sync.Once
	file_YM_Common_CommonMessage_proto_rawDescData = file_YM_Common_CommonMessage_proto_rawDesc
)

func file_YM_Common_CommonMessage_proto_rawDescGZIP() []byte {
	file_YM_Common_CommonMessage_proto_rawDescOnce.Do(func() {
		file_YM_Common_CommonMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_YM_Common_CommonMessage_proto_rawDescData)
	})
	return file_YM_Common_CommonMessage_proto_rawDescData
}

var file_YM_Common_CommonMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_YM_Common_CommonMessage_proto_goTypes = []any{
	(*PKeyString)(nil),                    // 0: YM.Common.PKeyString
	(*PKeyInt)(nil),                       // 1: YM.Common.PKeyInt
	(*PKeyLong)(nil),                      // 2: YM.Common.PKeyLong
	(*KeyValuePair)(nil),                  // 3: YM.Common.KeyValuePair
	(*Dictionary)(nil),                    // 4: YM.Common.Dictionary
	(*NullableBool)(nil),                  // 5: YM.Common.NullableBool
	(*NullableDecimal)(nil),               // 6: YM.Common.NullableDecimal
	(*NullableUInt)(nil),                  // 7: YM.Common.NullableUInt
	(*ResponseBase)(nil),                  // 8: YM.Common.ResponseBase
	(*ResponseBaseWithInt)(nil),           // 9: YM.Common.ResponseBaseWithInt
	(*ResponseBaseWithLong)(nil),          // 10: YM.Common.ResponseBaseWithLong
	(*ResponseBaseWithString)(nil),        // 11: YM.Common.ResponseBaseWithString
	(*ResponseBaseWithKeyDictionary)(nil), // 12: YM.Common.ResponseBaseWithKeyDictionary
	(*NullableInt)(nil),                   // 13: YM.Common.NullableInt
	(*NullableTimestamp)(nil),             // 14: YM.Common.NullableTimestamp
	(*GenericLongCollection)(nil),         // 15: YM.Common.GenericLongCollection
	(*GenericIntCollection)(nil),          // 16: YM.Common.GenericIntCollection
	(*GenericStringCollection)(nil),       // 17: YM.Common.GenericStringCollection
	(*ResponseBaseWithBool)(nil),          // 18: YM.Common.ResponseBaseWithBool
	(*PageFilter)(nil),                    // 19: YM.Common.PageFilter
	(*ChunkStream)(nil),                   // 20: YM.Common.ChunkStream
	(*DateRange)(nil),                     // 21: YM.Common.DateRange
	(*NullableLong)(nil),                  // 22: YM.Common.NullableLong
	(*NullableDouble)(nil),                // 23: YM.Common.NullableDouble
	(*timestamppb.Timestamp)(nil),         // 24: google.protobuf.Timestamp
}
var file_YM_Common_CommonMessage_proto_depIdxs = []int32{
	3,  // 0: YM.Common.Dictionary.Data:type_name -> YM.Common.KeyValuePair
	4,  // 1: YM.Common.ResponseBaseWithKeyDictionary.Data:type_name -> YM.Common.Dictionary
	24, // 2: YM.Common.NullableTimestamp.Data:type_name -> google.protobuf.Timestamp
	24, // 3: YM.Common.DateRange.DateStart:type_name -> google.protobuf.Timestamp
	24, // 4: YM.Common.DateRange.DateEnd:type_name -> google.protobuf.Timestamp
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_YM_Common_CommonMessage_proto_init() }
func file_YM_Common_CommonMessage_proto_init() {
	if File_YM_Common_CommonMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_YM_Common_CommonMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_YM_Common_CommonMessage_proto_goTypes,
		DependencyIndexes: file_YM_Common_CommonMessage_proto_depIdxs,
		MessageInfos:      file_YM_Common_CommonMessage_proto_msgTypes,
	}.Build()
	File_YM_Common_CommonMessage_proto = out.File
	file_YM_Common_CommonMessage_proto_rawDesc = nil
	file_YM_Common_CommonMessage_proto_goTypes = nil
	file_YM_Common_CommonMessage_proto_depIdxs = nil
}
