// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: YM.Common/ConstantMessage.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountStatus int32

const (
	AccountStatus_AccountStatusNone AccountStatus = 0
	AccountStatus_Active            AccountStatus = 1
	AccountStatus_Inactive          AccountStatus = 2
	AccountStatus_Suspend           AccountStatus = 3
	AccountStatus_SelfExclude       AccountStatus = 4
	AccountStatus_Delete            AccountStatus = 5
	AccountStatus_Pending           AccountStatus = 6
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "AccountStatusNone",
		1: "Active",
		2: "Inactive",
		3: "Suspend",
		4: "SelfExclude",
		5: "Delete",
		6: "Pending",
	}
	AccountStatus_value = map[string]int32{
		"AccountStatusNone": 0,
		"Active":            1,
		"Inactive":          2,
		"Suspend":           3,
		"SelfExclude":       4,
		"Delete":            5,
		"Pending":           6,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_YM_Common_ConstantMessage_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_YM_Common_ConstantMessage_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_YM_Common_ConstantMessage_proto_rawDescGZIP(), []int{0}
}

type IdendityProvider int32

const (
	IdendityProvider_IdendityProviderNone IdendityProvider = 0
	IdendityProvider_Google               IdendityProvider = 1
	IdendityProvider_Telegram             IdendityProvider = 2
)

// Enum value maps for IdendityProvider.
var (
	IdendityProvider_name = map[int32]string{
		0: "IdendityProviderNone",
		1: "Google",
		2: "Telegram",
	}
	IdendityProvider_value = map[string]int32{
		"IdendityProviderNone": 0,
		"Google":               1,
		"Telegram":             2,
	}
)

func (x IdendityProvider) Enum() *IdendityProvider {
	p := new(IdendityProvider)
	*p = x
	return p
}

func (x IdendityProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdendityProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_YM_Common_ConstantMessage_proto_enumTypes[1].Descriptor()
}

func (IdendityProvider) Type() protoreflect.EnumType {
	return &file_YM_Common_ConstantMessage_proto_enumTypes[1]
}

func (x IdendityProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdendityProvider.Descriptor instead.
func (IdendityProvider) EnumDescriptor() ([]byte, []int) {
	return file_YM_Common_ConstantMessage_proto_rawDescGZIP(), []int{1}
}

var File_YM_Common_ConstantMessage_proto protoreflect.FileDescriptor

var file_YM_Common_ConstantMessage_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x59, 0x4d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x59, 0x4d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x77, 0x0a, 0x0d,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a,
	0x11, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x53,
	0x65, 0x6c, 0x66, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x10, 0x06, 0x2a, 0x46, 0x0a, 0x10, 0x49, 0x64, 0x65, 0x6e, 0x64, 0x69, 0x74,
	0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x64, 0x65,
	0x6e, 0x64, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x10, 0x02, 0x42, 0x33, 0x5a,
	0x1d, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x59, 0x4d, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0xaa, 0x02,
	0x11, 0x59, 0x4d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_YM_Common_ConstantMessage_proto_rawDescOnce sync.Once
	file_YM_Common_ConstantMessage_proto_rawDescData = file_YM_Common_ConstantMessage_proto_rawDesc
)

func file_YM_Common_ConstantMessage_proto_rawDescGZIP() []byte {
	file_YM_Common_ConstantMessage_proto_rawDescOnce.Do(func() {
		file_YM_Common_ConstantMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_YM_Common_ConstantMessage_proto_rawDescData)
	})
	return file_YM_Common_ConstantMessage_proto_rawDescData
}

var file_YM_Common_ConstantMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_YM_Common_ConstantMessage_proto_goTypes = []any{
	(AccountStatus)(0),    // 0: YM.Common.AccountStatus
	(IdendityProvider)(0), // 1: YM.Common.IdendityProvider
}
var file_YM_Common_ConstantMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_YM_Common_ConstantMessage_proto_init() }
func file_YM_Common_ConstantMessage_proto_init() {
	if File_YM_Common_ConstantMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_YM_Common_ConstantMessage_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_YM_Common_ConstantMessage_proto_goTypes,
		DependencyIndexes: file_YM_Common_ConstantMessage_proto_depIdxs,
		EnumInfos:         file_YM_Common_ConstantMessage_proto_enumTypes,
	}.Build()
	File_YM_Common_ConstantMessage_proto = out.File
	file_YM_Common_ConstantMessage_proto_rawDesc = nil
	file_YM_Common_ConstantMessage_proto_goTypes = nil
	file_YM_Common_ConstantMessage_proto_depIdxs = nil
}
